import test from 'node:test';import assert from 'node:assert/strict';import {mapButtonRect} from '../integrations/hardfire/drawn-buttons.js';
test('maps iframe-local bounds to full screenshot with zoom and device scaling',()=>{assert.deepEqual(mapButtonRect({x:10,y:20,width:40,height:30},{x:100,y:50,width:400,height:200},{width:200,height:100},{width:1600,height:1000},{width:800,height:500}),{x:240,y:180,width:160,height:120});});
test('clips cropped controls to screenshot and rejects controls fully outside',()=>{const args=[{x:0,y:0,width:100,height:100},{width:100,height:100},{width:100,height:100},{width:100,height:100}];assert.deepEqual(mapButtonRect({x:-20,y:-10,width:40,height:30},...args),{x:0,y:0,width:20,height:20});assert.equal(mapButtonRect({x:120,y:20,width:10,height:10},...args),null);});
import vm from 'node:vm';import {inspectDrawnButtons} from '../providers/pragmatic/drawn-buttons.js';
test('drawn scan rejects hidden, disabled and inactive controls and merges handlers on one object',()=>{
 const XTButton=function(){},CATButton=function(){},UIButton=function(){},UISprite=function(){},Camera=function(){};
 const make=(name,{active=true,disabled=false,hidden=false}={})=>{const widget={enabled:true,gameObject:{activeInHierarchy:true},pixiObject:{visible:!hidden,renderable:true,worldAlpha:1,getBounds:()=>({x:10,y:20,width:30,height:40})},spriteName:name};const go={name,activeInHierarchy:active,layer:0,transform:{parent:null},collider:{enabled:true,GetTransformedCenterAndSize:()=>({center:{x:25,y:40,z:0},size:{x:30,y:40,z:1}})},GetComponent:()=>({target:widget}),GetComponentsInChildren:()=>[widget]};return {gameObject:go,enabled:!disabled,eventToCode:{name:'E_'+name}};};
 const visible=make('visible'),inactive=make('inactive',{active:false}),disabled=make('disabled',{disabled:true}),hidden=make('hidden',{hidden:true});const cat={...visible,eventToCode:null};
 const camera={enabled:true,gameObject:{activeInHierarchy:true},depth:1,cullingMask:1,WorldToScreenPoint:p=>p};
 const root={GetComponentsInChildren:c=>c===Camera?[camera]:c===XTButton?[visible,inactive,disabled,hidden]:c===CATButton?[cat]:[]};
 const ctx={XTButton,CATButton,UIButton,UISprite,Camera,globalRuntime:{sceneRoots:[root]},UHTScreen:{width:100,height:100},innerWidth:100,innerHeight:100,document:{querySelectorAll:()=>[{width:100,height:100,getBoundingClientRect:()=>({x:0,y:0,width:100,height:100})}]}};
 const result=vm.runInNewContext(`(${inspectDrawnButtons.toString()})()`,ctx);assert.equal(result.controls.length,1);assert.equal(result.controls[0].name,'visible');assert.equal(result.controls[0].handlers.length,2);assert.equal(result.controls[0].clickable,'RUNTIME_COLLIDER');
});

test('a collider can associate its drawing through six structural parents',()=>{const CATButton=function(){},UISprite=function(){},Camera=function(){};const widget={enabled:true,gameObject:{activeInHierarchy:true},pixiObject:{visible:true,renderable:true,worldAlpha:1,getBounds:()=>({x:10,y:20,width:30,height:40})},spriteName:'feature'};let parent=null;for(let i=6;i>=1;i--){const depth=i;parent={parent,gameObject:{name:'wrapper'+i,GetComponentsInChildren:()=>depth===6?[widget]:[]}};}const go={name:'target',activeInHierarchy:true,layer:0,transform:{parent},collider:{enabled:true,GetTransformedCenterAndSize:()=>({center:{x:25,y:40,z:0},size:{x:30,y:40,z:1}})},GetComponent:()=>null,GetComponentsInChildren:()=>[]};const camera={enabled:true,gameObject:{activeInHierarchy:true},depth:1,cullingMask:1,WorldToScreenPoint:p=>p};const root={GetComponentsInChildren:c=>c===Camera?[camera]:c===CATButton?[{gameObject:go}]:[]};const result=vm.runInNewContext('('+inspectDrawnButtons.toString()+')()',{CATButton,UISprite,Camera,globalRuntime:{sceneRoots:[root]},UHTScreen:{width:100,height:100},innerWidth:100,innerHeight:100,document:{querySelectorAll:()=>[{width:100,height:100,getBoundingClientRect:()=>({x:0,y:0,width:100,height:100})}]}});assert.equal(result.controls.length,1);assert.equal(result.controls[0].drawing_association,'ANCESTOR_6');});

test('invisible collider sprites do not prevent association with a visible ancestor',()=>{const CATButton=function(){},UISprite=function(){},Camera=function(){};const placeholder={enabled:true,gameObject:{activeInHierarchy:true},pixiObject:{visible:false},spriteName:'hit-only'},visual={enabled:true,gameObject:{activeInHierarchy:true},pixiObject:{visible:true,renderable:true,worldAlpha:1,getBounds:()=>({x:10,y:20,width:30,height:40})},spriteName:'feature'};const ancestor={parent:null,gameObject:{name:'drawing',GetComponentsInChildren:()=>[visual]}};const parent={parent:ancestor,gameObject:{name:'colliders',GetComponentsInChildren:()=>[placeholder]}};const go={name:'target',activeInHierarchy:true,layer:0,transform:{parent},collider:{enabled:true,GetTransformedCenterAndSize:()=>({center:{x:25,y:40,z:0},size:{x:30,y:40,z:1}})},GetComponent:()=>null,GetComponentsInChildren:()=>[placeholder]};const camera={enabled:true,gameObject:{activeInHierarchy:true},depth:1,cullingMask:1,WorldToScreenPoint:p=>p};const root={GetComponentsInChildren:c=>c===Camera?[camera]:c===CATButton?[{gameObject:go}]:[]};const result=vm.runInNewContext('('+inspectDrawnButtons.toString()+')()',{CATButton,UISprite,Camera,globalRuntime:{sceneRoots:[root]},UHTScreen:{width:100,height:100},innerWidth:100,innerHeight:100,document:{querySelectorAll:()=>[{width:100,height:100,getBoundingClientRect:()=>({x:0,y:0,width:100,height:100})}]}});assert.equal(result.controls.length,1);assert.equal(result.controls[0].drawing_association,'ANCESTOR_2');assert.deepEqual([...result.controls[0].sprite_names],['feature']);});
