import test from 'node:test';import assert from 'node:assert/strict';import {filterKnownControls,knownControlKind} from '../providers/pragmatic/known-controls.js';
const c=(name,path='',event=null)=>({name,path,handlers:[{event}]});
test('known base UI is removed including generic child names with known ancestry',()=>{const items=[c('StartSpin_Button','','Evt_DataToCode_Pressed_Spin'),c('BetUp_Button','','Evt_DataToCode_SmartIncreaseBet'),c('BetDown_Button','','Evt_DataToCode_SmartDecreaseBet'),c('AutoplayOpenButton'),c('Paytable_Button_Open'),c('ButtonOpen','GUI/SoundButtons/SoundOn/ButtonOpen'),c('ButtonOpen','GUI/Settings/ButtonOpen'),c('Normal','GUI/GameSpeed/Normal'),c('HiperPlayDisabled','GUI/AutoplayOpenButton/HiperPlayDisabled'),c('MoneyAndCoinsSwitcher')];const p=filterKnownControls(items);assert.equal(p.keep.length,0);assert.equal(p.discarded.length,items.length);assert.ok(p.discarded.every(x=>x.discard_reason));});
test('purchases, ante, picker, collect and bonus spin are preserved despite common-looking names',()=>{const items=[c('ColliderBuy','Game/FeaturePurchase/MainButton'),c('Level0Button','Game/BuyButtons/BetLevel'),c('StartSpin_Button','Game/Bonus/SpinButtons','Evt_DataToCode_Pressed_Spin'),c('ButtonOpen','Game/AnteBet/MainButton'),c('Normal','Game/FreeSpins/Choice'),c('ButtonOpen','','Evt_DataToCode_BonusResultWindow_PressedCollect')];assert.deepEqual(filterKnownControls(items).keep,items);});
test('unknown generic buttons are not discarded merely because names are ambiguous',()=>{for(const item of [c('ButtonOpen'),c('OptionButton'),c('Level0Button'),c('Normal'),c('Collider0')])assert.equal(knownControlKind(item),null);});
test('explicit known settings and speed button names work without ancestry',()=>{assert.equal(knownControlKind(c('SettingsButton')),'settings');assert.equal(knownControlKind(c('MenuButton')),'settings');assert.equal(knownControlKind(c('TurboButton')),'speed');assert.equal(knownControlKind(c('QuickSpinButton')),'speed');});
test('standard UI wrappers containing SpecialFeature are not mistaken for economic controls',()=>{assert.equal(knownControlKind(c('ButtonOpen','GUI/VisibleInSpecialFeature/SoundButtons/ButtonOpen')),'sound');assert.equal(knownControlKind(c('Paytable_Button_Open','GUI/VisibleInSpecialFeature/Paytable/Paytable_Button_Open')),'paytable');assert.equal(knownControlKind(c('ButtonOpen','GUI_mobile/AnchoredRight/MenuButton/MenuOpenClose/ButtonOpen')),'settings');assert.equal(knownControlKind(c('Continue','Game/SpecialFeature/Continue')) ,null);});

test('known bet adjusters remain excluded inside purchases without hiding ante choices',()=>{assert.equal(knownControlKind(c('BetUp_Button','Game/FeaturePurchase/BetButtons','Evt_DataToCode_SmartIncreaseBet')),'base_bet');assert.equal(knownControlKind(c('Level1Button','Game/AnteBet/BetLevel')),null);});

test('generic hyperplay placeholders are recognized through their base UI ancestry',()=>{assert.equal(knownControlKind(c('Disabled','GUI/Interface/BottomBar/Elements/HyperPlay/Disabled')),'speed');});
