import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
test('3 Oaks BFS discovers an unknown menu, executes a purchase, waits for base and closes owned sessions',async()=>{
 const {runThreeOaksExplorer}=await import('../integrations/hardfire/three-oaks-explorer.js');let closes=0,clicks=[];const dir=await mkdtemp(path.join(os.tmpdir(),'oaks-bfs-'));
 const entry=(name,terminal=false)=>({request:{url:'https://betman-demo.head.3oaks.com/betman-demo/gs/fixture/desktop/id/demo/',postData:{text:JSON.stringify({command:'play',action:{name,params:{}}})}},response:{status:200,content:{text:JSON.stringify({status:{code:'OK'},context:{current:terminal?'spins':'bonus',round_finished:terminal,actions:terminal?['spin']:['respin'],last_action:name,last_args:{}}})}}});
 const factory=async()=>{let menu=false,entries=[],ticks=0;return {tabId:1,scan:async()=>({supported:true,viewport:{width:800,height:600},anteBet:0,controls:entries.length===1?[]:[{path:menu?'menu/unknown-option':'root/unknown-opener',name:'unknown',handlers:[],hit_rect:{x:10,y:20,width:60,height:30}}],unresolved:[]}),entries:async()=>{if(ticks++>2&&entries.length===1)entries.push(entry('bonus_spins_stop',true));return entries;},click:async control=>{clicks.push(control.path);if(!menu)menu=true;else{menu=false;entries.push(entry('buy_spin'));ticks=0;}},close:async()=>{closes++;}};};
 try{const result=await runThreeOaksExplorer({}, {gameUrl:'https://3oaks.com/game/fixture',artifactDir:dir,maxActions:2,maxDepth:3,sessionFactory:factory,waitOptions:{quietMs:1,pollMs:1,activeMs:500}});assert.ok(clicks.includes('menu/unknown-option'));assert.equal(result.edges[1].operation.kind,'purchase');assert.equal(result.edges[1].operation.ok,true,JSON.stringify(result));assert.equal(closes,2);}finally{await rm(dir,{recursive:true,force:true});}
});test('a failed HAR save never closes the retained tab on later cleanup attempts',async()=>{
 const {createThreeOaksCloser}=await import('../integrations/hardfire/three-oaks-session.js');let saved=0,closed=0;const close=createThreeOaksCloser({tabId:42,hasCapture:()=>true,save:async()=>{saved++;throw Error('disk write failed')},closeTab:async()=>{closed++}});for(let i=0;i<2;i++)await assert.rejects(close(),error=>error.retainedTabId===42);assert.equal(saved,1);assert.equal(closed,0);
});test('normal Spin becomes an observed continuation during a bought bonus',async()=>{
 const {runThreeOaksExplorer}=await import('../integrations/hardfire/three-oaks-explorer.js');const dir=await mkdtemp(path.join(os.tmpdir(),'oaks-respin-'));let clicks=0;const factory=async()=>{const entries=[];let menu=false;const play=(name,terminal=false)=>({request:{url:'https://betman-demo.head.3oaks.com/betman-demo/gs/fixture/desktop/id/demo/',postData:{text:JSON.stringify({command:'play',action:{name,params:{}}})}},response:{status:200,content:{text:JSON.stringify({status:{code:'OK'},context:{current:terminal?'spins':'bonus',round_finished:terminal,actions:terminal?['spin']:['respin'],last_action:name,last_args:{}}})}}});return {tabId:1,entries:async()=>entries,scan:async()=>({supported:true,anteBet:0,controls:entries.length&&!JSON.parse(entries.at(-1).response.content.text).context.round_finished?[{path:'runner/spin',semantic:'spin',handlers:[],hit_rect:{x:0,y:0,width:10,height:10}}]:[{path:menu?'menu/option':'root/menu',handlers:[],hit_rect:{x:0,y:0,width:10,height:10}}],unresolved:[]}),click:async c=>{if(c.path==='runner/spin'){clicks++;entries.push(play('respin',clicks===3))}else if(!menu)menu=true;else entries.push(play('buy_spin'));},close:async()=>{}}};
 try{const r=await runThreeOaksExplorer({}, {gameUrl:'https://3oaks.com/game/fixture',artifactDir:dir,maxActions:2,sessionFactory:factory,waitOptions:{quietMs:1,pollMs:1,activeMs:500}});assert.equal(clicks,3);assert.equal(r.edges[1].operation.ok,true);}finally{await rm(dir,{recursive:true,force:true});}
});