import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const load=()=>import('../providers/three-oaks/discovery.js');
test('3 Oaks scanner finds nested live controls and excludes invisible or disabled controls',async()=>{
 const {inspectThreeOaksControls}=await load();
 const rect={x:0,y:0,width:800,height:600};
 const node=(name,extra={})=>({name,children:[],visible:true,renderable:true,alpha:1,interactive:true,_events:{pointertap:{fn:function onTap(){}}},getBounds:()=>({x:20,y:30,width:100,height:50}),...extra});
 const buy=node('purchase-opener'),option=node('unknown-new-option'),hidden=node('hidden',{visible:false}),disabled=node('disabled',{enabled:false});
 const stage=node('root',{interactive:false,_events:{},children:[buy,{name:'menu',visible:true,children:[option]},hidden,disabled]});
 const sandbox={app:{stage,canvas:{getBoundingClientRect:()=>rect},renderer:{screen:rect},board:{buyFeatureButton:buy}},GR:{UI:{model:{get:()=>false}}},innerWidth:800,innerHeight:600,document:{querySelectorAll:()=>[]}};
 const out=vm.runInNewContext('('+inspectThreeOaksControls.toString()+')()',sandbox);
 assert.equal(out.supported,true);assert.deepEqual(Array.from(out.controls,c=>c.name),['purchase-opener','unknown-new-option']);assert.equal(out.controls[0].semantic,'buyFeatureButton');assert.equal(out.controls[0].hit_rect.width,100);
});
test('3 Oaks scanner does not manufacture controls or accept missing canvas geometry',async()=>{
 const {inspectThreeOaksControls}=await load();const out=vm.runInNewContext('('+inspectThreeOaksControls.toString()+')()',{app:{stage:{children:[]}},document:{querySelectorAll:()=>[]},innerWidth:100,innerHeight:100});assert.equal(out.supported,false);
});
test('standard UI ownership is filtered while shop, antebet and unknown menu options remain',async()=>{
 const {filterThreeOaksControls}=await load();const controls=['spin','autoplay','settings','shopButton','anteBetButton','new-option'].map(semantic=>({semantic,path:semantic}));const result=filterThreeOaksControls(controls);assert.deepEqual(result.keep.map(c=>c.semantic),['shopButton','anteBetButton','new-option']);
 assert.equal(filterThreeOaksControls([{name:'SpinButton',path:'unknown/SpinButton'}]).keep.length,1);
});
test('successful purchase requires matching acknowledgment and ordinary spins are separate',async()=>{
 const {readThreeOaksOperations}=await import('../providers/three-oaks/protocol.js');const fixture=JSON.parse(await readFile(new URL('./fixtures/three-oaks-scatters-sanitized.json',import.meta.url),'utf8'));const out=readThreeOaksOperations(fixture.log.entries);assert.equal(out.operations.filter(o=>o.kind==='purchase'&&o.accepted).length,3);assert.equal(out.operations.filter(o=>o.kind==='antebet'&&o.accepted).length,8);
});
test('wrong last_action, missing echo, and HTTP errors cannot confirm a purchase',async()=>{
 const {readThreeOaksOperations}=await import('../providers/three-oaks/protocol.js');const entry=(status,context)=>({request:{url:'https://betman-demo.head.3oaks.com/betman-demo/gs/fixture/desktop/id/demo/',postData:{text:JSON.stringify({command:'play',action:{name:'buy_spin',params:{selected_mode:0}}})}},response:{status,content:{text:JSON.stringify({status:{code:'OK'},context})}}});for(const e of [entry(429,{last_action:'buy_spin',last_args:{selected_mode:0}}),entry(200,{last_action:'spin',last_args:{selected_mode:0}}),entry(200,{last_action:'buy_spin'})])assert.equal(readThreeOaksOperations([e]).operations[0].accepted,false);
});
test('natural bonus and its return to base never become purchases',async()=>{
 const {readThreeOaksOperations}=await import('../providers/three-oaks/protocol.js');const fixture=JSON.parse(await readFile(new URL('./fixtures/three-oaks-natural-sanitized.json',import.meta.url),'utf8'));const out=readThreeOaksOperations(fixture.log.entries);assert.equal(out.operations.filter(o=>o.kind==='purchase').length,0);assert.equal(out.baseTerminal,true);assert.ok(out.operations.some(o=>o.action==='bonus_spins_stop'));
});
test('3 Oaks permits only public demo game pages without copied sessions',async()=>{
 const {assertThreeOaksDemoUrl}=await load();assert.equal(assertThreeOaksDemoUrl('https://3oaks.com/games/lady-fortune/'),'https://3oaks.com/games/lady-fortune/');for(const u of ['https://example.com/games/test/','https://3oaks.com/games/test/?token=secret','https://betman-demo.head.3oaks.com/betman-demo/gs/test/desktop/id/demo/'])assert.throws(()=>assertThreeOaksDemoUrl(u));
});test('transparent 3 Oaks click targets retain visible parent art and verified custom hit areas',async()=>{
 const {inspectThreeOaksControls}=await load();const rect={x:0,y:0,width:800,height:600},bounds={x:20,y:30,width:100,height:50};
 const button={name:'transparent-hit',alpha:0,visible:true,interactive:true,_events:{click:{fn:function purchase(){}}},getBounds:()=>bounds,worldTransform:{applyInverse:p=>p},hitArea:{contains:(x,y)=>x>=20&&x<=120&&y>=30&&y<=80},children:[]};const art={name:'visible-art',visible:true,alpha:1,getBounds:()=>bounds,children:[]};const stage={name:'root',visible:true,alpha:1,getBounds:()=>bounds,children:[art,button]};button.parent=stage;art.parent=stage;
 const out=vm.runInNewContext('('+inspectThreeOaksControls.toString()+')()',{app:{stage,canvas:{getBoundingClientRect:()=>rect},renderer:{screen:rect},board:{}},document:{querySelectorAll:()=>[]},innerWidth:800,innerHeight:600});assert.equal(out.controls.length,1);assert.ok(out.controls[0].hit_points.length);assert.equal(out.controls[0].drawing_source,'visible-parent-art');
});test('shared runner parent ownership identifies the normal spin without matching labels',async()=>{
 const {inspectThreeOaksControls}=await load();const rect={x:0,y:0,width:800,height:600};const spin={name:'x',componentName:'SpinButton',interactive:true,children:[],_events:{mouseup:{fn:function onPointerUp(){}}},getBounds:()=>({x:10,y:20,width:50,height:50})};const parent={name:'runner',children:[spin],spinButton:spin,quickSpin:{},autogame:{}};spin.parent=parent;const stage={children:[parent]};parent.parent=stage;
 const out=vm.runInNewContext('('+inspectThreeOaksControls.toString()+')()',{app:{stage,canvas:{getBoundingClientRect:()=>rect},renderer:{screen:rect},board:{}},document:{querySelectorAll:()=>[]},innerWidth:800,innerHeight:600});assert.equal(out.controls[0]?.semantic,'spin');
});
test('pending responses do not reject operations or reuse an earlier terminal base context',async()=>{
 const {readThreeOaksOperations}=await import('../providers/three-oaks/protocol.js');const fixture=JSON.parse(await readFile(new URL('./fixtures/three-oaks-natural-sanitized.json',import.meta.url),'utf8'));const pending={request:{url:fixture.log.entries[0].request.url,postData:{text:JSON.stringify({command:'play',action:{name:'buy_spin',params:{}}})}},response:{status:0,content:{}}};const out=readThreeOaksOperations([...fixture.log.entries,pending]);assert.equal(out.last.pending,true);assert.equal(out.baseTerminal,false);
});test('empty PIXI containers with native rectangular hit areas remain discoverable',async()=>{
 const {inspectThreeOaksControls}=await load();const rect={x:0,y:0,width:800,height:600};const target={name:'intro',interactive:true,children:[],_events:{pointerdown:{fn:function skip(){}}},getBounds:()=>({x:0,y:0,width:0,height:0}),hitArea:{x:100,y:100,width:200,height:100,contains:(x,y)=>x>=100&&x<=300&&y>=100&&y<=200},worldTransform:{a:1,b:0,c:0,d:1,tx:0,ty:0,applyInverse:p=>p}};const stage={children:[target]};target.parent=stage;const out=vm.runInNewContext('('+inspectThreeOaksControls.toString()+')()',{app:{stage,canvas:{getBoundingClientRect:()=>rect},renderer:{screen:rect},board:{}},document:{querySelectorAll:()=>[]},innerWidth:800,innerHeight:600});assert.equal(out.controls.length,1);assert.equal(out.controls[0].hit_rect.width,200);
});test('known runner texture controls are filtered without inheriting them into client feature buttons',async()=>{
 const {inspectThreeOaksControls,filterThreeOaksControls}=await load();const rect={x:0,y:0,width:800,height:600};const button=()=>({interactive:true,children:[{texture:{textureCacheIds:['gr_ui_sound_on']},children:[]}],_events:{pointertap:{fn:function click(){}}},getBounds:()=>({x:20,y:30,width:100,height:50})});const sound=button(),feature=button(),grLayer={children:[sound]};sound.parent=grLayer;const stage={children:[grLayer,feature]};grLayer.parent=stage;feature.parent=stage;
 const out=vm.runInNewContext('('+inspectThreeOaksControls.toString()+')()',{app:{stage,grLayer,canvas:{getBoundingClientRect:()=>rect},renderer:{screen:rect},board:{buyFeatureButton:feature}},document:{querySelectorAll:()=>[]},innerWidth:800,innerHeight:600});const result=filterThreeOaksControls(out.controls);assert.equal(result.discarded.length,1);assert.equal(result.discarded[0].discard_reason,'sound');assert.equal(result.keep[0].semantic,'buyFeatureButton');
});test('absolute HAR body references are resolved and hash mismatches cannot confirm purchases',async()=>{
 const {readThreeOaksOperations}=await import('../providers/three-oaks/protocol.js');const {createHash}=await import('node:crypto');const text=JSON.stringify({status:{code:'OK'},context:{last_action:'buy_spin',last_args:{selected_mode:0},current:'spins',round_finished:true,actions:['spin']}}),url='https://betman-demo.head.3oaks.com/betman-demo/gs/fixture/desktop/id/demo/';const entries=[{request:{url:'https://static.3oaks.com/body.json'},response:{status:200,content:{text}}},{request:{url,postData:{text:JSON.stringify({command:'play',action:{name:'buy_spin',params:{selected_mode:0}}})}},response:{status:200,content:{_bodyReference:{entry:0,sha256:createHash('sha256').update(text).digest('hex')}}}}];assert.equal(readThreeOaksOperations(entries).last.accepted,true);entries[1].response.content._bodyReference.sha256='bad';assert.equal(readThreeOaksOperations(entries).last.accepted,false);
});test('runner sound is recognized through its bound runtime handler, even with generated textures',async()=>{
 const {inspectThreeOaksControls,filterThreeOaksControls}=await load();const rect={x:0,y:0,width:800,height:600};const proto={onPointerUp:function(){GR.UI.view.sound.click()}};const sound=Object.assign(Object.create(proto),{interactive:true,children:[],getBounds:()=>({x:20,y:30,width:100,height:50})});sound._onPointerUp=sound.onPointerUp.bind(sound);sound._events={mouseup:{fn:sound._onPointerUp}};const grLayer={children:[sound]};sound.parent=grLayer;const stage={children:[grLayer]};grLayer.parent=stage;
 const out=vm.runInNewContext('('+inspectThreeOaksControls.toString()+')()',{app:{stage,grLayer,canvas:{getBoundingClientRect:()=>rect},renderer:{screen:rect},board:{}},document:{querySelectorAll:()=>[]},innerWidth:800,innerHeight:600});assert.equal(filterThreeOaksControls(out.controls).discarded[0]?.discard_reason,'sound');
});test('selector purchase captures preserve four observed wire choices without guessing UI indices',async()=>{
 const {readThreeOaksOperations}=await import('../providers/three-oaks/protocol.js');const fixture=JSON.parse(await readFile(new URL('./fixtures/three-oaks-selector-sanitized.json',import.meta.url),'utf8'));const out=readThreeOaksOperations(fixture.log.entries);const purchases=out.operations.filter(o=>o.kind==='purchase'&&o.accepted);assert.equal(purchases.length,4);assert.deepEqual(purchases.map(o=>o.params.selected_mode),[3,1,2,0]);
});