import {measure} from '../../lib/performance.js';
let surfaceTail=Promise.resolve();
export async function withSurfaceLock(fn){const previous=surfaceTail;let release;surfaceTail=new Promise(r=>{release=r});await measure('surface.queue',()=>previous);try{return await measure('surface.hold',fn);}finally{release();}}
export function bitmapHasPaint(bitmap){let colored=0,total=0;const colors=new Set();for(let i=0;i+3<bitmap.length;i+=4){total++;const b=bitmap[i],g=bitmap[i+1],r=bitmap[i+2];if(Math.max(r,g,b)>24){colored++;colors.add((r>>3)+','+(g>>3)+','+(b>>3));}}return total>0&&colored/total>.005&&colors.size>3;}
export async function waitForPaint(a,{timeoutMs=60000}={}){const start=a.now();let consecutive=0,lastRefresh=-Infinity,checks=0;while(a.now()-start<timeoutMs){checks++;if(await measure('paint.sample',()=>a.sample())){if(++consecutive>=2)return {ok:true,checks,elapsedMs:a.now()-start};}else{consecutive=0;if(a.now()-lastRefresh>=2000){await measure('paint.refresh',()=>a.refresh());lastRefresh=a.now();}}await measure('wait.paint',()=>a.sleep(250));}throw Error('SURFACE_NOT_PAINTED: game viewport remained empty/black');}
async function ensurePaintedImpl(controller,tabId){const scoped=controller.withTab(tabId),wc=scoped._wc();await measure('surface.activate',()=>controller.tabs.activate(tabId));wc.invalidate?.();return waitForPaint({now:()=>Date.now(),sleep:ms=>new Promise(r=>setTimeout(r,ms)),refresh:async()=>{wc.invalidate?.();const status=await scoped.status();if(typeof status.visible==='boolean'&&scoped.browser)await scoped.browser(status.visible?'visible':'hidden');},sample:async()=>{
 const rect=await measure('paint.rect',()=>wc.executeJavaScript(`(()=>{const f=[...document.querySelectorAll('iframe')].find(e=>e.src.startsWith('https://demogamesfree.pragmaticplay.net/'));const r=f?.getBoundingClientRect();return r?{x:Math.max(0,Math.round(r.x)),y:Math.max(0,Math.round(r.y)),width:Math.round(r.width),height:Math.round(r.height)}:{x:0,y:0,width:innerWidth,height:innerHeight};})()`));if(rect.width<=0||rect.height<=0)return false;const image=await measure('paint.capture',()=>wc.capturePage(rect));if(image.isEmpty())return false;return measure('paint.bitmap',()=>bitmapHasPaint(image.resize({width:160}).toBitmap()));}});}

export function ensurePainted(controller,tabId){return measure('surface.paint',()=>ensurePaintedImpl(controller,tabId));}
